# Generated by Django 4.0.3 on 2022-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='pictures'),
        ),
    ]
