# Generated by Django 4.0.3 on 2022-03-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_event_options_event_host_alter_event_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
