# Generated by Django 4.0.3 on 2022-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_event_alter_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
    ]
