# Generated by Django 4.0.4 on 2022-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
