# Generated by Django 4.0.4 on 2022-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_event_date_event_capacity_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
